Fix undefined reference to inlined function
In a call to an inline function, it's unspecified whether the external
or the inline definition is used. So we need to declare the inline
function as static to not check that an external definition is defined
somewhere in the linked program.