Fix warning stm32_common_mcu_init missing declaration
stm32_common_system.c:119:7: warning: implicit declaration of function 'stm32_common_mcu_init' [-Wimplicit-function-declaration]
       stm32_common_mcu_init();